# Setup
title:               Pingus Douradus
tagline:             'Latindo'
description:         'Au'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pingus Douradus
  url:               https://twitter.com/pingusdouradus
  email:             pingusdouradus@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
